package server

// Code generated by genbackendsimpl. DO NOT EDIT.

import (
	"testing"

	"github.com/uht-hack/unsure/db"
)

type backendsImpl struct {
	uhtDB *db.UhtDB
}

func MakeBackends(
	uhtDB *db.UhtDB,
) *backendsImpl {
	return &backendsImpl{
		uhtDB: uhtDB,
	}
}

type backendsOption func(*backendsImpl)

func NewBackendsForTesting(tb testing.TB, opts ...backendsOption) *backendsImpl {
	var b backendsImpl
	for _, opt := range opts {
		opt(&b)
	}
	return &b
}

func WithUhtDB(uhtDB *db.UhtDB) backendsOption {
	return func(b *backendsImpl) {
		b.uhtDB = uhtDB
	}
}

func (b *backendsImpl) UhtDB() *db.UhtDB {
	if b == nil {
		return nil
	}
	return b.uhtDB
}
