// Code generated by glean from glean.go:3. DO NOT EDIT.
package matches

import (
	"context"
	"database/sql"
)

const cols = " `id`, `status`, `players` "
const selectPrefix = "select " + cols + " from matches where "

func Lookup(ctx context.Context, dbc dbc, id int64) (*Match, error) {
	return lookupWhere(ctx, dbc, "id=?", id)
}

// lookupWhere queries the matches table with the provided where clause, then scans
// and returns a single row.
func lookupWhere(ctx context.Context, dbc dbc, where string, args ...interface{}) (*Match, error) {
	return scan(dbc.QueryRowContext(ctx, selectPrefix+where, args...))
}

// listWhere queries the matches table with the provided where clause, then scans
// and returns all the rows.
func listWhere(ctx context.Context, dbc dbc, where string, args ...interface{}) ([]Match, error) {

	rows, err := dbc.QueryContext(ctx, selectPrefix+where, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var res []Match
	for rows.Next() {
		r, err := scan(rows)
		if err != nil {
			return nil, err
		}
		res = append(res, *r)
	}

	return res, rows.Err()
}

func scan(row row) (*Match, error) {
	var g glean

	err := row.Scan(&g.id, &g.status, &g.players)
	if err != nil {
		return nil, err
	}

	return &Match{
		id:      g.id,
		status:  g.status,
		players: g.players,
	}, nil
}

// dbc is a common interface for *sql.DB and *sql.Tx.
type dbc interface {
	QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// row is a common interface for *sql.Rows and *sql.Row.
type row interface {
	Scan(dest ...interface{}) error
}
