// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uht.proto

package uhtpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import reflexpb "github.com/luno/reflex/reflexpb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoundStatus int32

const (
	RoundStatus_ROUND_STATUS_UNKNOWN   RoundStatus = 0
	RoundStatus_ROUND_STATUS_JOIN      RoundStatus = 1
	RoundStatus_ROUND_STATUS_JOINED    RoundStatus = 2
	RoundStatus_ROUND_STATUS_COLLECT   RoundStatus = 3
	RoundStatus_ROUND_STATUS_COLLECTED RoundStatus = 4
	RoundStatus_ROUND_STATUS_SUBMIT    RoundStatus = 5
	RoundStatus_ROUND_STATUS_SUBMITTED RoundStatus = 6
	RoundStatus_ROUND_STATUS_SUCCESS   RoundStatus = 7
	RoundStatus_ROUND_STATUS_FAILED    RoundStatus = 8
	RoundStatus_ROUND_STATUS_SENTINEL  RoundStatus = 9
)

var RoundStatus_name = map[int32]string{
	0: "ROUND_STATUS_UNKNOWN",
	1: "ROUND_STATUS_JOIN",
	2: "ROUND_STATUS_JOINED",
	3: "ROUND_STATUS_COLLECT",
	4: "ROUND_STATUS_COLLECTED",
	5: "ROUND_STATUS_SUBMIT",
	6: "ROUND_STATUS_SUBMITTED",
	7: "ROUND_STATUS_SUCCESS",
	8: "ROUND_STATUS_FAILED",
	9: "ROUND_STATUS_SENTINEL",
}
var RoundStatus_value = map[string]int32{
	"ROUND_STATUS_UNKNOWN":   0,
	"ROUND_STATUS_JOIN":      1,
	"ROUND_STATUS_JOINED":    2,
	"ROUND_STATUS_COLLECT":   3,
	"ROUND_STATUS_COLLECTED": 4,
	"ROUND_STATUS_SUBMIT":    5,
	"ROUND_STATUS_SUBMITTED": 6,
	"ROUND_STATUS_SUCCESS":   7,
	"ROUND_STATUS_FAILED":    8,
	"ROUND_STATUS_SENTINEL":  9,
}

func (x RoundStatus) String() string {
	return proto.EnumName(RoundStatus_name, int32(x))
}
func (RoundStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Round struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MatchId              int64                `protobuf:"varint,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Index                int64                `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Team                 string               `protobuf:"bytes,4,opt,name=team,proto3" json:"team,omitempty"`
	Status               RoundStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=uhtpb.RoundStatus" json:"status,omitempty"`
	State                *RoundState          `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Error                string               `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Round) Reset()         { *m = Round{} }
func (m *Round) String() string { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()    {}
func (*Round) Descriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{1}
}
func (m *Round) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Round.Unmarshal(m, b)
}
func (m *Round) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Round.Marshal(b, m, deterministic)
}
func (dst *Round) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Round.Merge(dst, src)
}
func (m *Round) XXX_Size() int {
	return xxx_messageInfo_Round.Size(m)
}
func (m *Round) XXX_DiscardUnknown() {
	xxx_messageInfo_Round.DiscardUnknown(m)
}

var xxx_messageInfo_Round proto.InternalMessageInfo

func (m *Round) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Round) GetMatchId() int64 {
	if m != nil {
		return m.MatchId
	}
	return 0
}

func (m *Round) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Round) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Round) GetStatus() RoundStatus {
	if m != nil {
		return m.Status
	}
	return RoundStatus_ROUND_STATUS_UNKNOWN
}

func (m *Round) GetState() *RoundState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Round) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Round) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Round) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type RoundState struct {
	Players              []*RoundPlayerState `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RoundState) Reset()         { *m = RoundState{} }
func (m *RoundState) String() string { return proto.CompactTextString(m) }
func (*RoundState) ProtoMessage()    {}
func (*RoundState) Descriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{2}
}
func (m *RoundState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundState.Unmarshal(m, b)
}
func (m *RoundState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundState.Marshal(b, m, deterministic)
}
func (dst *RoundState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundState.Merge(dst, src)
}
func (m *RoundState) XXX_Size() int {
	return xxx_messageInfo_RoundState.Size(m)
}
func (m *RoundState) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundState.DiscardUnknown(m)
}

var xxx_messageInfo_RoundState proto.InternalMessageInfo

func (m *RoundState) GetPlayers() []*RoundPlayerState {
	if m != nil {
		return m.Players
	}
	return nil
}

type RoundPlayerState struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rank                 int32            `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Parts                map[string]int32 `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Included             bool             `protobuf:"varint,4,opt,name=included,proto3" json:"included,omitempty"`
	Collected            bool             `protobuf:"varint,5,opt,name=collected,proto3" json:"collected,omitempty"`
	Submitted            bool             `protobuf:"varint,6,opt,name=submitted,proto3" json:"submitted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoundPlayerState) Reset()         { *m = RoundPlayerState{} }
func (m *RoundPlayerState) String() string { return proto.CompactTextString(m) }
func (*RoundPlayerState) ProtoMessage()    {}
func (*RoundPlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{3}
}
func (m *RoundPlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundPlayerState.Unmarshal(m, b)
}
func (m *RoundPlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundPlayerState.Marshal(b, m, deterministic)
}
func (dst *RoundPlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundPlayerState.Merge(dst, src)
}
func (m *RoundPlayerState) XXX_Size() int {
	return xxx_messageInfo_RoundPlayerState.Size(m)
}
func (m *RoundPlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundPlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_RoundPlayerState proto.InternalMessageInfo

func (m *RoundPlayerState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoundPlayerState) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *RoundPlayerState) GetParts() map[string]int32 {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *RoundPlayerState) GetIncluded() bool {
	if m != nil {
		return m.Included
	}
	return false
}

func (m *RoundPlayerState) GetCollected() bool {
	if m != nil {
		return m.Collected
	}
	return false
}

func (m *RoundPlayerState) GetSubmitted() bool {
	if m != nil {
		return m.Submitted
	}
	return false
}

type CollectRoundReq struct {
	RoundId              int64    `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectRoundReq) Reset()         { *m = CollectRoundReq{} }
func (m *CollectRoundReq) String() string { return proto.CompactTextString(m) }
func (*CollectRoundReq) ProtoMessage()    {}
func (*CollectRoundReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{4}
}
func (m *CollectRoundReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRoundReq.Unmarshal(m, b)
}
func (m *CollectRoundReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRoundReq.Marshal(b, m, deterministic)
}
func (dst *CollectRoundReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRoundReq.Merge(dst, src)
}
func (m *CollectRoundReq) XXX_Size() int {
	return xxx_messageInfo_CollectRoundReq.Size(m)
}
func (m *CollectRoundReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRoundReq.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRoundReq proto.InternalMessageInfo

func (m *CollectRoundReq) GetRoundId() int64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

type CollectRoundRes struct {
	Players              []*CollectPlayer `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CollectRoundRes) Reset()         { *m = CollectRoundRes{} }
func (m *CollectRoundRes) String() string { return proto.CompactTextString(m) }
func (*CollectRoundRes) ProtoMessage()    {}
func (*CollectRoundRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{5}
}
func (m *CollectRoundRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRoundRes.Unmarshal(m, b)
}
func (m *CollectRoundRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRoundRes.Marshal(b, m, deterministic)
}
func (dst *CollectRoundRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRoundRes.Merge(dst, src)
}
func (m *CollectRoundRes) XXX_Size() int {
	return xxx_messageInfo_CollectRoundRes.Size(m)
}
func (m *CollectRoundRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRoundRes.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRoundRes proto.InternalMessageInfo

func (m *CollectRoundRes) GetPlayers() []*CollectPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

type CollectPlayer struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parts                map[string]int32 `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Rank                 int64            `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CollectPlayer) Reset()         { *m = CollectPlayer{} }
func (m *CollectPlayer) String() string { return proto.CompactTextString(m) }
func (*CollectPlayer) ProtoMessage()    {}
func (*CollectPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_uht_e21d0121fe703a13, []int{6}
}
func (m *CollectPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectPlayer.Unmarshal(m, b)
}
func (m *CollectPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectPlayer.Marshal(b, m, deterministic)
}
func (dst *CollectPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectPlayer.Merge(dst, src)
}
func (m *CollectPlayer) XXX_Size() int {
	return xxx_messageInfo_CollectPlayer.Size(m)
}
func (m *CollectPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_CollectPlayer proto.InternalMessageInfo

func (m *CollectPlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectPlayer) GetParts() map[string]int32 {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *CollectPlayer) GetRank() int64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "uhtpb.Empty")
	proto.RegisterType((*Round)(nil), "uhtpb.Round")
	proto.RegisterType((*RoundState)(nil), "uhtpb.RoundState")
	proto.RegisterType((*RoundPlayerState)(nil), "uhtpb.RoundPlayerState")
	proto.RegisterMapType((map[string]int32)(nil), "uhtpb.RoundPlayerState.PartsEntry")
	proto.RegisterType((*CollectRoundReq)(nil), "uhtpb.CollectRoundReq")
	proto.RegisterType((*CollectRoundRes)(nil), "uhtpb.CollectRoundRes")
	proto.RegisterType((*CollectPlayer)(nil), "uhtpb.CollectPlayer")
	proto.RegisterMapType((map[string]int32)(nil), "uhtpb.CollectPlayer.PartsEntry")
	proto.RegisterEnum("uhtpb.RoundStatus", RoundStatus_name, RoundStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UhtClient is the client API for Uht service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UhtClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stream(ctx context.Context, in *reflexpb.StreamRequest, opts ...grpc.CallOption) (Uht_StreamClient, error)
	RoundData(ctx context.Context, in *CollectRoundReq, opts ...grpc.CallOption) (*CollectRoundRes, error)
}

type uhtClient struct {
	cc *grpc.ClientConn
}

func NewUhtClient(cc *grpc.ClientConn) UhtClient {
	return &uhtClient{cc}
}

func (c *uhtClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/uhtpb.Uht/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uhtClient) Stream(ctx context.Context, in *reflexpb.StreamRequest, opts ...grpc.CallOption) (Uht_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Uht_serviceDesc.Streams[0], "/uhtpb.Uht/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &uhtStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Uht_StreamClient interface {
	Recv() (*reflexpb.Event, error)
	grpc.ClientStream
}

type uhtStreamClient struct {
	grpc.ClientStream
}

func (x *uhtStreamClient) Recv() (*reflexpb.Event, error) {
	m := new(reflexpb.Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uhtClient) RoundData(ctx context.Context, in *CollectRoundReq, opts ...grpc.CallOption) (*CollectRoundRes, error) {
	out := new(CollectRoundRes)
	err := c.cc.Invoke(ctx, "/uhtpb.Uht/RoundData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UhtServer is the server API for Uht service.
type UhtServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	Stream(*reflexpb.StreamRequest, Uht_StreamServer) error
	RoundData(context.Context, *CollectRoundReq) (*CollectRoundRes, error)
}

func RegisterUhtServer(s *grpc.Server, srv UhtServer) {
	s.RegisterService(&_Uht_serviceDesc, srv)
}

func _Uht_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UhtServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uhtpb.Uht/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UhtServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Uht_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(reflexpb.StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UhtServer).Stream(m, &uhtStreamServer{stream})
}

type Uht_StreamServer interface {
	Send(*reflexpb.Event) error
	grpc.ServerStream
}

type uhtStreamServer struct {
	grpc.ServerStream
}

func (x *uhtStreamServer) Send(m *reflexpb.Event) error {
	return x.ServerStream.SendMsg(m)
}

func _Uht_RoundData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRoundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UhtServer).RoundData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uhtpb.Uht/RoundData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UhtServer).RoundData(ctx, req.(*CollectRoundReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Uht_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uhtpb.Uht",
	HandlerType: (*UhtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Uht_Ping_Handler,
		},
		{
			MethodName: "RoundData",
			Handler:    _Uht_RoundData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Uht_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "uht.proto",
}

func init() { proto.RegisterFile("uht.proto", fileDescriptor_uht_e21d0121fe703a13) }

var fileDescriptor_uht_e21d0121fe703a13 = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0x38, 0x89, 0xa7, 0xd0, 0xba, 0x4b, 0x2f, 0xae, 0x85, 0xd4, 0xc8, 0x42, 0x22,
	0xaa, 0x2a, 0x07, 0x82, 0x40, 0x05, 0x09, 0xa1, 0x90, 0x18, 0x29, 0x10, 0x92, 0xca, 0x4e, 0xc4,
	0x63, 0xe4, 0xc4, 0xdb, 0xc4, 0xaa, 0x6f, 0xb5, 0xd7, 0x55, 0xf3, 0x03, 0x3c, 0xf3, 0x0d, 0x3c,
	0xf1, 0x13, 0xfc, 0x1b, 0xf2, 0xae, 0xdd, 0x34, 0x17, 0x84, 0xc4, 0x93, 0x67, 0xe6, 0x9c, 0x99,
	0xf1, 0x9c, 0xd9, 0x5d, 0x10, 0x93, 0x39, 0xd1, 0xc2, 0x28, 0x20, 0x01, 0x12, 0x92, 0x39, 0x09,
	0x27, 0xca, 0xe9, 0x2c, 0x08, 0x66, 0x2e, 0x6e, 0xd0, 0xe0, 0x24, 0xb9, 0x6a, 0x10, 0xc7, 0xc3,
	0x31, 0xb1, 0xbc, 0x90, 0xf1, 0x94, 0xf3, 0x99, 0x43, 0xe6, 0xc9, 0x44, 0x9b, 0x06, 0x5e, 0xc3,
	0x4d, 0xfc, 0xa0, 0x11, 0xe1, 0x2b, 0x17, 0xdf, 0x65, 0x9f, 0x70, 0x92, 0x19, 0x8c, 0xad, 0x56,
	0x40, 0xd0, 0xbd, 0x90, 0x2c, 0xd4, 0xdf, 0x3c, 0x08, 0x46, 0x90, 0xf8, 0x36, 0xda, 0x05, 0xde,
	0xb1, 0x65, 0xae, 0xc6, 0xd5, 0x8b, 0x06, 0xef, 0xd8, 0xe8, 0x04, 0xaa, 0x9e, 0x45, 0xa6, 0xf3,
	0xb1, 0x63, 0xcb, 0x3c, 0x8d, 0x56, 0xa8, 0xdf, 0xb5, 0xd1, 0x01, 0x08, 0x8e, 0x6f, 0xe3, 0x3b,
	0xb9, 0x48, 0xe3, 0xcc, 0x41, 0x08, 0x4a, 0x04, 0x5b, 0x9e, 0x5c, 0xaa, 0x71, 0x75, 0xd1, 0xa0,
	0x36, 0x3a, 0x83, 0x72, 0x4c, 0x2c, 0x92, 0xc4, 0xb2, 0x50, 0xe3, 0xea, 0xbb, 0x4d, 0xa4, 0xd1,
	0x71, 0x34, 0xda, 0xd2, 0xa4, 0x88, 0x91, 0x31, 0xd0, 0x73, 0x10, 0x52, 0x0b, 0xcb, 0xe5, 0x1a,
	0x57, 0xdf, 0x69, 0xee, 0xaf, 0x53, 0xb1, 0xc1, 0xf0, 0xb4, 0x3d, 0x8e, 0xa2, 0x20, 0x92, 0x2b,
	0xb4, 0x13, 0x73, 0xd0, 0x5b, 0x80, 0x69, 0x84, 0x2d, 0x82, 0xed, 0xb1, 0x45, 0xe4, 0x2a, 0xad,
	0xa1, 0x68, 0x4c, 0x36, 0x2d, 0x97, 0x4d, 0x1b, 0xe6, 0xb2, 0x19, 0x62, 0xc6, 0x6e, 0x91, 0x34,
	0x35, 0x09, 0xed, 0x3c, 0x55, 0xfc, 0x77, 0x6a, 0xc6, 0x6e, 0x11, 0xf5, 0x03, 0xc0, 0xf2, 0x07,
	0xd1, 0x4b, 0xa8, 0x84, 0xae, 0xb5, 0xc0, 0x51, 0x2c, 0x73, 0xb5, 0x62, 0x7d, 0xa7, 0x79, 0xfc,
	0x70, 0x88, 0x4b, 0x0a, 0xb1, 0x51, 0x72, 0x9e, 0xfa, 0x9d, 0x07, 0x69, 0x1d, 0x4d, 0xa5, 0xf4,
	0x2d, 0x0f, 0xd3, 0x6d, 0x88, 0x06, 0xb5, 0xd3, 0x58, 0x64, 0xf9, 0xd7, 0x74, 0x17, 0x82, 0x41,
	0x6d, 0x74, 0x01, 0x42, 0x68, 0x45, 0x24, 0x96, 0x8b, 0xb4, 0x9b, 0xfa, 0x97, 0x6e, 0xda, 0x65,
	0x4a, 0xd2, 0x7d, 0x12, 0x2d, 0x0c, 0x96, 0x80, 0x14, 0xa8, 0x3a, 0xfe, 0xd4, 0x4d, 0x6c, 0x6c,
	0xd3, 0x85, 0x55, 0x8d, 0x7b, 0x1f, 0x3d, 0x05, 0x71, 0x1a, 0xb8, 0x2e, 0x9e, 0x12, 0x6c, 0xd3,
	0xbd, 0x55, 0x8d, 0x65, 0x20, 0x45, 0xe3, 0x64, 0xe2, 0x39, 0x24, 0x45, 0xcb, 0x0c, 0xbd, 0x0f,
	0x28, 0x17, 0x00, 0xcb, 0x66, 0x48, 0x82, 0xe2, 0x35, 0x5e, 0x64, 0x63, 0xa4, 0x66, 0xba, 0xbb,
	0x5b, 0xcb, 0x4d, 0x70, 0x36, 0x06, 0x73, 0xde, 0xf1, 0x17, 0x9c, 0x7a, 0x0e, 0x7b, 0x6d, 0xd6,
	0x84, 0xfe, 0xbe, 0x81, 0x6f, 0xd2, 0x23, 0x18, 0xa5, 0xf6, 0xf8, 0xfe, 0x60, 0x56, 0xa8, 0xdf,
	0xb5, 0xd5, 0xd6, 0x3a, 0x3b, 0x46, 0xda, 0xba, 0xf8, 0x07, 0x99, 0x1c, 0x19, 0x91, 0x09, 0xb2,
	0x54, 0xfe, 0x17, 0x07, 0x8f, 0x57, 0xa0, 0xad, 0xb2, 0xbf, 0xce, 0x25, 0xe6, 0x69, 0xcd, 0xd3,
	0x6d, 0x35, 0xb7, 0xe8, 0x9b, 0x6f, 0x8b, 0xdd, 0x10, 0x6a, 0xff, 0xbf, 0x36, 0x67, 0x3f, 0x78,
	0xd8, 0x79, 0x70, 0x65, 0x90, 0x0c, 0x07, 0xc6, 0x60, 0xd4, 0xef, 0x8c, 0xcd, 0x61, 0x6b, 0x38,
	0x32, 0xc7, 0xa3, 0xfe, 0x97, 0xfe, 0xe0, 0x5b, 0x5f, 0x2a, 0xa0, 0x43, 0xd8, 0x5f, 0x41, 0x3e,
	0x0f, 0xba, 0x7d, 0x89, 0x43, 0xc7, 0xf0, 0x64, 0x23, 0xac, 0x77, 0x24, 0x7e, 0xa3, 0x52, 0x7b,
	0xd0, 0xeb, 0xe9, 0xed, 0xa1, 0x54, 0x44, 0x0a, 0x1c, 0x6d, 0x43, 0xf4, 0x8e, 0x54, 0xda, 0x28,
	0x67, 0x8e, 0x3e, 0x7e, 0xed, 0x0e, 0x25, 0x61, 0x23, 0x89, 0x01, 0x69, 0x52, 0x79, 0xa3, 0x95,
	0x39, 0x6a, 0xb7, 0x75, 0xd3, 0x94, 0x2a, 0x1b, 0xe5, 0x3e, 0xb5, 0xba, 0x3d, 0xbd, 0x23, 0x55,
	0xd1, 0x09, 0x1c, 0xae, 0xa6, 0xe8, 0xfd, 0x61, 0xb7, 0xaf, 0xf7, 0x24, 0xb1, 0xf9, 0x93, 0x83,
	0xe2, 0x68, 0x4e, 0xd0, 0x33, 0x28, 0x5d, 0x3a, 0xfe, 0x0c, 0x3d, 0xca, 0x16, 0x43, 0x9f, 0x35,
	0x65, 0xc5, 0x53, 0x0b, 0xe8, 0x0d, 0x94, 0x4d, 0x12, 0xa5, 0x2f, 0xd2, 0xb1, 0x96, 0xbf, 0x88,
	0x1a, 0x8b, 0x18, 0xf8, 0x26, 0xc1, 0x31, 0x51, 0xf6, 0x96, 0x80, 0x7e, 0x8b, 0x7d, 0xa2, 0x16,
	0x5e, 0x70, 0xe8, 0x3d, 0x88, 0x54, 0xf7, 0x8e, 0x45, 0x2c, 0x74, 0xb4, 0xba, 0xfb, 0xfc, 0x98,
	0x2a, 0xdb, 0xe3, 0xb1, 0x5a, 0x98, 0x94, 0xe9, 0xe3, 0xf1, 0xea, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf8, 0x84, 0xac, 0xad, 0xd0, 0x05, 0x00, 0x00,
}
